[background]
blur = 2
opacity = 0.95

[colors.bright]
black = "#414868"
blue = "#7AA2F7"
cyan = "#7DCFFF"
green = "#9ECE6A"
magenta = "#BB9AF7"
red = "#F7768E"
white = "#C0CAF5"
yellow = "#E0AF68"

[colors.normal]
black = "#1B1B2F"
blue = "#7AA2F7"
cyan = "#7DCFFF"
green = "#9ECE6A"
magenta = "#BB9AF7"
red = "#F7768E"
white = "#A9B1D6"
yellow = "#E0AF68"

[colors.primary]
background = "#1E1E2E"
foreground = "#C0CAF5"

[cursor]
blink = true
color = "#FFCC00"
style = "Beam"

[font.bold]
family = "JetBrains Mono Nerd Font"
size = 12.0
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
size = 12.0
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
size = 12.0
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
size = 12.0
style = "Regular"

